### ISSUE TITLE
Feature request: Generate multilevel data with no clusters

### ISSUE THREAD

**Issue by b1azk0** [rpsychologist/powerlmm#13]
Hi, would it be possible to include options for generating non longitudinal multilevel datasets (without cluster groups etc).

What I'm trying to simulate is a 2 level data set with a level 2 predictor (subject level) predicting a level 1 outcome (observation level).
I like the possibility to control all the parameters (like ICCs or ESs) and could use it in the context of purely continuous variables at different levels of measurement.

Or maybe it's already possible, but I can't figure out how?

All the best!

**Comment by b1azk0** [comment]
As a follow up and maybe some more detail, I posted the following as a comment in [your powerlmm-0.4.0 post](http://rpsychologist.com/do-you-need-multilevel-powerlmm-0-4-0)

> Hi, could you please help me out and explain if there is a possibility to simulate data and power for studies where with cont. predictors at different levels of analysis (e.g.level1 and level2) - specifically without any groups? To be more specific I'm trying to simulate `y` (as in `y ~ 1 + (1|id)`) for a given between / within variance ratio, and then add to it continuous `x1` and `x2` covariates and analyse `y ~ x1 + x2 + (x1 | id)`. I'd really use some advice and help. Been stuck with this problem for a week now. Thank you

If all the above is possible with the use of your other parameters like ICCs, var_ratio and so on - please let me know how should I approach this

**Comment by rpsychologist** [comment]
Hi, I don't think powerlmm is a good fit for such a simulation. The focus of powerlmm is on longitudinal data. A more general purpose simulation-package like _simglm_ is probably a better option for you model.

**Comment by b1azk0** [comment]
So, there is no easy workaround for it? I'm interested in power and more in data simulation at given parameters.
Anyway thanks for the suggestion. I didn't knew `simglm` package. Will look into it.
