### ISSUE TITLE
dev version of installation error (... non-zero exit status)

### ISSUE THREAD

**Issue by rnorouzian** [rpsychologist/powerlmm#19]
Dear Dr. Magnusson,

I'm trying to install the dev version of your powerlmm package from github. However, I get the following error. Just was wondering if am I missing something? (multiple friends of mine faced the same issue)

```
library(remotes)
remotes::install_github("rpsychologist/powerlmm", dependencies = TRUE)

Error: Failed to install 'powerlmm' from GitHub:
  (converted from warning) installation of package ‘C:/Users/AppData/Local/Temp/RtmpKUee0F/file4ed83f5e3806/
powerlmm_0.4.0.9000.tar.gz’ had non-zero exit status
```

**Comment by rpsychologist** [comment]
No, it's my fault - I accidently pushed an unfished commit to master :) I've merged #20 which fixes this error.
